apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    workspaces.kcp.dev/internal-name: workspace1
  name: workspace1-owner
rules:
- apiGroups:
  - tenancy.kcp.dev
  resourceNames:
  - workspace1
  resources:
  - workspaces
  verbs:
  - get
  - delete
- apiGroups:
  - tenancy.kcp.dev
  resourceNames:
  - workspace1
  resources:
  - workspaces/content
  verbs:
  - view
  - edit
