apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kcp-syncer-{{ .Workspace }}-{{ .Cluster }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kcp-syncer-{{ .Workspace }}
subjects:
{{- if .CertsEnabled }}
- kind: Group
  apiGroup: rbac.authorization.k8s.io
  name: {{ .Group }}
{{- else }}
- kind: ServiceAccount
  name: {{ .Workspace }}-sa
  namespace: kcp-ocm
{{- end }}
