apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kcp-ocm-integration-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kcp-ocm-integration-controller
subjects:
  - kind: ServiceAccount
    name: kcp-ocm-integration-controller-sa
    namespace: open-cluster-management
