apiVersion: v1
kind: Namespace
metadata:
  name: default

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: default
spec:
  replicas: 3 # tells deployment to run 2 pods matching the template
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: quay.io/bitnami/nginx:1.14.2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
