apiVersion: v1
kind: Namespace
metadata:
  name: nginx
  labels:
    experimental.workloads.kcp.dev/scheduling-disabled: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: nginx
spec:
  replicas: 3 # tells deployment to run 2 pods matching the template
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: quay.io/skeeey/nginx:1.14.2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
