apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment--cluster1
  labels:
    kcp.dev/owned-by: nginx-deployment
    workloads.kcp.dev/cluster: cluster1
  clusterName: default:workspace1
spec:
  replicas: 1 # tells deployment to run 2 pods matching the template
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: quay.io/bitnami/nginx:1.14.2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
